"use client"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import RichTextEditor from "@/components/form-sections/rich-text-editor"

interface Step2Props {
  onNext: () => void
  onBack: () => void
}

export default function Step2ProjectPerformance({ onNext, onBack }: Step2Props) {
  return (
    <div className="space-y-6">
      {/* Section Header */}
      <h3 className="text-lg font-semibold text-[#008037]">Project performance during reporting period</h3>

      {/* Technical Section */}
      <div className="space-y-4">
        <h4 className="text-base font-semibold text-[#373737]">Technical</h4>

        <div className="space-y-2">
          <Label className="text-sm text-[#595959]">
            Description of project activities implemented during the reporting period.
          </Label>
          <RichTextEditor />
        </div>
      </div>

      {/* Carbon Credits Metrics */}
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label className="text-sm text-[#595959]">
            Carbon credits generated compared to the expected carbon credits from the project design document.
          </Label>
          <Input className="bg-[#f9f9f9] border-[#e8e8e8]" />
        </div>
        <div className="space-y-2">
          <Label className="text-sm text-[#595959]">
            Amount of carbon credits generated compared to the carbon credits generated by the project in the previous
            period.
          </Label>
          <Input className="bg-[#f9f9f9] border-[#e8e8e8]" />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label className="text-sm text-[#595959]">
            Amount of carbon Credit estimated ex-ante for the incoming project reporting period.
          </Label>
          <Input className="bg-[#f9f9f9] border-[#e8e8e8]" />
        </div>
        <div className="space-y-2">
          <Label className="text-sm text-[#595959]">
            Amount of greenhouse gas emissions reductions or removals achieved by the project within the reporting
            period.
          </Label>
          <Input className="bg-[#f9f9f9] border-[#e8e8e8]" />
        </div>
      </div>

      <div className="space-y-2">
        <Label className="text-sm text-[#595959]">
          Amount of greenhouse gas emissions reductions or removals expected from the project in the incoming reporting
          period.
        </Label>
        <Input className="bg-[#f9f9f9] border-[#e8e8e8]" />
      </div>

      {/* Navigation Buttons */}
      <div className="flex justify-center gap-4 pt-4">
        <Button variant="outline" onClick={onBack} className="px-8 bg-transparent">
          GO BACK
        </Button>
        <Button onClick={onNext} className="bg-[#008037] hover:bg-[#006b2d] text-white px-8">
          SAVE AND CONTINUE
        </Button>
      </div>
    </div>
  )
}
